[build-system]
requires = ["setuptools>=42,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DP5"
version = "0.1.2"
requires-python = ">=3.9, <=3.11"
description = "A short description of the project"
readme = "readme.md"
authors = [
    {name = "Kristaps Ermanis"},
    {name = "Alexander Howarth"}
]
maintainers = [
    {name = "Ruslan Kotlyarov", email = "rk582@cam.ac.uk"}
]

dependencies = [
        "tomli",
        "numpy==1.26.4",
        "rdkit==2025.9.3",
        "setuptools<81",
        "lmfit<2",
        "matplotlib<4",
        "scipy>=1.10,<1.16",
        "nmrglue<1",
        "tqdm<5",
        "scikit-learn<1.8",
        "pathos<0.4",
        "pandas<3",
        "statsmodels<0.15",
        "tensorflow==2.14.0",
        "keras==2.14.0",
        "tensorflow-metal==1.1.0; sys_platform == 'darwin' and platform_machine == 'arm64'",
        "dill<0.5",
        "joblib<2",
        "networkx>=3,<4"

    ]

[project.optional-dependencies]
dev = [
    "sphinx==7.4.7",
    "sphinx-rtd-theme==2.0",
]

[project.urls]
Documentation = "https://ruslankotl.github.io/DP5/index.html"
Source = "https://github.com/ruslankotl/DP5"



[project.scripts]
pydp4 = "dp5.load_config:main"

[tool.setuptools.packages.find]
include = ["dp5"]
